### ISSUE TITLE
Missing sof passuq after word with ketiv-qere

### ISSUE THREAD

**Issue by camilstaps** [parabible/parabible-client#74]
Just a very minor thing: in Gen 9:21, the last word of the verse has a ketiv-qere. Parabible correctly shows only the consonants for this word, but does not display the sof passuq. Is this intentional?

![2022-08-04-085422_345x41](https://user-images.githubusercontent.com/1202754/182782863-c7ad68c0-f89b-46f0-a95e-172bdecad14f.png)

Also e.g. Jdg 7:21.

**Comment by jcuenod** [comment]
Thanks @camilstaps, it's not intentional! I'll take a look at that but, to be honest, I've rebuilt the whole system twice in the last few years to set the backend up to support more versions/translations and to run searches faster with lower memory footprint. There's an alpha site of the first rebuild up at dev.parabible.com (but if it crashes, I'm not phased). In that version, the sof pasuq is present. I'm not sure if it's just an improvement to the importer or whether there is some other bug operating in the current production version, but thanks for calling it to my attention!

**Comment by camilstaps** [comment]
Oh that’s great! Then you really don’t have to spend time on fixing it in the current version, it’s a very minor detail 😄
